<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Ex. Expose Object</title>

<style type="text/css">
body {
	background-color: #fff;
	margin: 40px;
	font-family: Lucida Grande, Verdana, Sans-serif;
	font-size: 14px;
	color: #4F5155;
}

a {
	color: #003399;
	background-color: transparent;
	font-weight: normal;
}

h1 {
	color: #000;
	background-color: transparent;
	border-bottom: 1px solid #D0D0D0;
	font-size: 24px;
	font-weight: bold;
	margin: 24px 0 2px 0;
	padding: 5px 0 6px 0;
}

code {
	font-family: Monaco, Verdana, Sans-serif;
	font-size: 12px;
	background-color: #f9f9f9;
	border: 1px solid #D0D0D0;
	color: #002166;
	display: block;
	margin: 14px 0 14px 0;
	padding: 12px 10px 12px 10px;
}

dl {
	margin-left: 30px;
	background-color: #eee;
}

dt {
	font-weight: bold;
}

dd {
	margin-bottom: 10px;
}

pre {
	font-style: italic;
	font-size: 9px;
	margin-left: 10px;
	color: black;
	background-color: #999;
	padding: 6px;
}

.box {
	border: 1px solid #999;
	margin-left: 20px;
	margin-top: 10px;
	padding: 5px;
}
</style>
</head>
<body>

<h1>Ex. Expose Object</h1>
[<a href="<?php echo site_url(''); ?>">Home</a>]
<p>
In RestIgniter there are two ways to expose an object:
</p>
<ol>
	<li>exposing an object class set in application/modules</li>
	<li>exposing a spark object class (set in sparks/...)</li>
</ol>
<p>
We are going to expose a simple chart object (called Chartex) packed as a spark.<br/>
First of all we need to make a spark following this easy <a href="http://getsparks.org/make-sparks" target="_blank">guide</a> (look sparks/chartex).<br/>
</p>
<h3>The object code</h3>
<?php $filename = 'sparks/chartex/0.0.1/models/chartex.php'; ?>
This is the object code <?php echo $filename; ?>:
<?php highlight_file($filename);?>


<h3>The configuration file</h3>
<?php $filename = 'sparks/chartex/0.0.1/config/chartex.php'; ?>
This is Chartex config file <?php echo $filename; ?>:
<?php highlight_file($filename);?>


<h3>The autoload file</h3>
<?php $filename = 'sparks/chartex/0.0.1/config/autoload.php'; ?>
This is Chartex autoload file <?php echo $filename; ?> which autoload both the model and the config file (pls read the note in the Documentation page):
<?php highlight_file($filename);?>

<h3>Allow the exposition</h3>
<?php $filename = 'application/config/restigniter.php'; ?>
This is RestIgniter config file <?php echo $filename; ?>: here we set the object that we allow to expose over REST:
<?php highlight_file($filename);?>

<h3>Exposed method for Chartex</h3>
The following lines are automatically generated by the RestIgniter using object reflection:
<div class="box">
<?php echo !empty($methods_list) ? $methods_list : 'No public methods in this REST service'; ?>
</div>
<p>
[<a href="<?php echo site_url(''); ?>">Home</a>]
</p>
</body>
</html>
